version: '3.8'

services:
  vue-app:
    container_name: tms-client-vuejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
